// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package carparts.proto;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CarPartsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:carparts.proto.CarParts)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    java.util.List<carparts.proto.Schema.CarPart> 
        getCarPartList();
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    carparts.proto.Schema.CarPart getCarPart(int index);
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    int getCarPartCount();
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    java.util.List<? extends carparts.proto.Schema.CarPartOrBuilder> 
        getCarPartOrBuilderList();
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    carparts.proto.Schema.CarPartOrBuilder getCarPartOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code carparts.proto.CarParts}
   */
  public  static final class CarParts extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:carparts.proto.CarParts)
      CarPartsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CarParts.newBuilder() to construct.
    private CarParts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarParts() {
      carPart_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CarParts(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                carPart_ = new java.util.ArrayList<carparts.proto.Schema.CarPart>();
                mutable_bitField0_ |= 0x00000001;
              }
              carPart_.add(
                  input.readMessage(carparts.proto.Schema.CarPart.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          carPart_ = java.util.Collections.unmodifiableList(carPart_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return carparts.proto.Schema.internal_static_carparts_proto_CarParts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return carparts.proto.Schema.internal_static_carparts_proto_CarParts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              carparts.proto.Schema.CarParts.class, carparts.proto.Schema.CarParts.Builder.class);
    }

    public static final int CARPART_FIELD_NUMBER = 1;
    private java.util.List<carparts.proto.Schema.CarPart> carPart_;
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    public java.util.List<carparts.proto.Schema.CarPart> getCarPartList() {
      return carPart_;
    }
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    public java.util.List<? extends carparts.proto.Schema.CarPartOrBuilder> 
        getCarPartOrBuilderList() {
      return carPart_;
    }
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    public int getCarPartCount() {
      return carPart_.size();
    }
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    public carparts.proto.Schema.CarPart getCarPart(int index) {
      return carPart_.get(index);
    }
    /**
     * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
     */
    public carparts.proto.Schema.CarPartOrBuilder getCarPartOrBuilder(
        int index) {
      return carPart_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < carPart_.size(); i++) {
        output.writeMessage(1, carPart_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < carPart_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, carPart_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof carparts.proto.Schema.CarParts)) {
        return super.equals(obj);
      }
      carparts.proto.Schema.CarParts other = (carparts.proto.Schema.CarParts) obj;

      boolean result = true;
      result = result && getCarPartList()
          .equals(other.getCarPartList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCarPartCount() > 0) {
        hash = (37 * hash) + CARPART_FIELD_NUMBER;
        hash = (53 * hash) + getCarPartList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static carparts.proto.Schema.CarParts parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static carparts.proto.Schema.CarParts parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static carparts.proto.Schema.CarParts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static carparts.proto.Schema.CarParts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static carparts.proto.Schema.CarParts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static carparts.proto.Schema.CarParts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static carparts.proto.Schema.CarParts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static carparts.proto.Schema.CarParts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static carparts.proto.Schema.CarParts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static carparts.proto.Schema.CarParts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static carparts.proto.Schema.CarParts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static carparts.proto.Schema.CarParts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(carparts.proto.Schema.CarParts prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code carparts.proto.CarParts}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:carparts.proto.CarParts)
        carparts.proto.Schema.CarPartsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return carparts.proto.Schema.internal_static_carparts_proto_CarParts_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return carparts.proto.Schema.internal_static_carparts_proto_CarParts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                carparts.proto.Schema.CarParts.class, carparts.proto.Schema.CarParts.Builder.class);
      }

      // Construct using carparts.proto.Schema.CarParts.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCarPartFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (carPartBuilder_ == null) {
          carPart_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          carPartBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return carparts.proto.Schema.internal_static_carparts_proto_CarParts_descriptor;
      }

      @java.lang.Override
      public carparts.proto.Schema.CarParts getDefaultInstanceForType() {
        return carparts.proto.Schema.CarParts.getDefaultInstance();
      }

      @java.lang.Override
      public carparts.proto.Schema.CarParts build() {
        carparts.proto.Schema.CarParts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public carparts.proto.Schema.CarParts buildPartial() {
        carparts.proto.Schema.CarParts result = new carparts.proto.Schema.CarParts(this);
        int from_bitField0_ = bitField0_;
        if (carPartBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            carPart_ = java.util.Collections.unmodifiableList(carPart_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.carPart_ = carPart_;
        } else {
          result.carPart_ = carPartBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof carparts.proto.Schema.CarParts) {
          return mergeFrom((carparts.proto.Schema.CarParts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(carparts.proto.Schema.CarParts other) {
        if (other == carparts.proto.Schema.CarParts.getDefaultInstance()) return this;
        if (carPartBuilder_ == null) {
          if (!other.carPart_.isEmpty()) {
            if (carPart_.isEmpty()) {
              carPart_ = other.carPart_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCarPartIsMutable();
              carPart_.addAll(other.carPart_);
            }
            onChanged();
          }
        } else {
          if (!other.carPart_.isEmpty()) {
            if (carPartBuilder_.isEmpty()) {
              carPartBuilder_.dispose();
              carPartBuilder_ = null;
              carPart_ = other.carPart_;
              bitField0_ = (bitField0_ & ~0x00000001);
              carPartBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCarPartFieldBuilder() : null;
            } else {
              carPartBuilder_.addAllMessages(other.carPart_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        carparts.proto.Schema.CarParts parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (carparts.proto.Schema.CarParts) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<carparts.proto.Schema.CarPart> carPart_ =
        java.util.Collections.emptyList();
      private void ensureCarPartIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          carPart_ = new java.util.ArrayList<carparts.proto.Schema.CarPart>(carPart_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          carparts.proto.Schema.CarPart, carparts.proto.Schema.CarPart.Builder, carparts.proto.Schema.CarPartOrBuilder> carPartBuilder_;

      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public java.util.List<carparts.proto.Schema.CarPart> getCarPartList() {
        if (carPartBuilder_ == null) {
          return java.util.Collections.unmodifiableList(carPart_);
        } else {
          return carPartBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public int getCarPartCount() {
        if (carPartBuilder_ == null) {
          return carPart_.size();
        } else {
          return carPartBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public carparts.proto.Schema.CarPart getCarPart(int index) {
        if (carPartBuilder_ == null) {
          return carPart_.get(index);
        } else {
          return carPartBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder setCarPart(
          int index, carparts.proto.Schema.CarPart value) {
        if (carPartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarPartIsMutable();
          carPart_.set(index, value);
          onChanged();
        } else {
          carPartBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder setCarPart(
          int index, carparts.proto.Schema.CarPart.Builder builderForValue) {
        if (carPartBuilder_ == null) {
          ensureCarPartIsMutable();
          carPart_.set(index, builderForValue.build());
          onChanged();
        } else {
          carPartBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder addCarPart(carparts.proto.Schema.CarPart value) {
        if (carPartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarPartIsMutable();
          carPart_.add(value);
          onChanged();
        } else {
          carPartBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder addCarPart(
          int index, carparts.proto.Schema.CarPart value) {
        if (carPartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarPartIsMutable();
          carPart_.add(index, value);
          onChanged();
        } else {
          carPartBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder addCarPart(
          carparts.proto.Schema.CarPart.Builder builderForValue) {
        if (carPartBuilder_ == null) {
          ensureCarPartIsMutable();
          carPart_.add(builderForValue.build());
          onChanged();
        } else {
          carPartBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder addCarPart(
          int index, carparts.proto.Schema.CarPart.Builder builderForValue) {
        if (carPartBuilder_ == null) {
          ensureCarPartIsMutable();
          carPart_.add(index, builderForValue.build());
          onChanged();
        } else {
          carPartBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder addAllCarPart(
          java.lang.Iterable<? extends carparts.proto.Schema.CarPart> values) {
        if (carPartBuilder_ == null) {
          ensureCarPartIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, carPart_);
          onChanged();
        } else {
          carPartBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder clearCarPart() {
        if (carPartBuilder_ == null) {
          carPart_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          carPartBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public Builder removeCarPart(int index) {
        if (carPartBuilder_ == null) {
          ensureCarPartIsMutable();
          carPart_.remove(index);
          onChanged();
        } else {
          carPartBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public carparts.proto.Schema.CarPart.Builder getCarPartBuilder(
          int index) {
        return getCarPartFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public carparts.proto.Schema.CarPartOrBuilder getCarPartOrBuilder(
          int index) {
        if (carPartBuilder_ == null) {
          return carPart_.get(index);  } else {
          return carPartBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public java.util.List<? extends carparts.proto.Schema.CarPartOrBuilder> 
           getCarPartOrBuilderList() {
        if (carPartBuilder_ != null) {
          return carPartBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(carPart_);
        }
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public carparts.proto.Schema.CarPart.Builder addCarPartBuilder() {
        return getCarPartFieldBuilder().addBuilder(
            carparts.proto.Schema.CarPart.getDefaultInstance());
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public carparts.proto.Schema.CarPart.Builder addCarPartBuilder(
          int index) {
        return getCarPartFieldBuilder().addBuilder(
            index, carparts.proto.Schema.CarPart.getDefaultInstance());
      }
      /**
       * <code>repeated .carparts.proto.CarPart carPart = 1;</code>
       */
      public java.util.List<carparts.proto.Schema.CarPart.Builder> 
           getCarPartBuilderList() {
        return getCarPartFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          carparts.proto.Schema.CarPart, carparts.proto.Schema.CarPart.Builder, carparts.proto.Schema.CarPartOrBuilder> 
          getCarPartFieldBuilder() {
        if (carPartBuilder_ == null) {
          carPartBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              carparts.proto.Schema.CarPart, carparts.proto.Schema.CarPart.Builder, carparts.proto.Schema.CarPartOrBuilder>(
                  carPart_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          carPart_ = null;
        }
        return carPartBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:carparts.proto.CarParts)
    }

    // @@protoc_insertion_point(class_scope:carparts.proto.CarParts)
    private static final carparts.proto.Schema.CarParts DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new carparts.proto.Schema.CarParts();
    }

    public static carparts.proto.Schema.CarParts getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarParts>
        PARSER = new com.google.protobuf.AbstractParser<CarParts>() {
      @java.lang.Override
      public CarParts parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarParts(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarParts> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarParts> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public carparts.proto.Schema.CarParts getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarPartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:carparts.proto.CarPart)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 vendorId = 2;</code>
     */
    int getVendorId();

    /**
     * <code>int32 partId = 3;</code>
     */
    int getPartId();

    /**
     * <code>string partName = 4;</code>
     */
    java.lang.String getPartName();
    /**
     * <code>string partName = 4;</code>
     */
    com.google.protobuf.ByteString
        getPartNameBytes();

    /**
     * <code>string partDescription = 5;</code>
     */
    java.lang.String getPartDescription();
    /**
     * <code>string partDescription = 5;</code>
     */
    com.google.protobuf.ByteString
        getPartDescriptionBytes();

    /**
     * <code>int32 inventoryCurrentCount = 6;</code>
     */
    int getInventoryCurrentCount();

    /**
     * <code>int32 inventoryDesiredCount = 7;</code>
     */
    int getInventoryDesiredCount();

    /**
     * <code>bool discontinued = 8;</code>
     */
    boolean getDiscontinued();

    /**
     * <code>bool onOrder = 9;</code>
     */
    boolean getOnOrder();
  }
  /**
   * Protobuf type {@code carparts.proto.CarPart}
   */
  public  static final class CarPart extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:carparts.proto.CarPart)
      CarPartOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CarPart.newBuilder() to construct.
    private CarPart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarPart() {
      vendorId_ = 0;
      partId_ = 0;
      partName_ = "";
      partDescription_ = "";
      inventoryCurrentCount_ = 0;
      inventoryDesiredCount_ = 0;
      discontinued_ = false;
      onOrder_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CarPart(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              vendorId_ = input.readInt32();
              break;
            }
            case 24: {

              partId_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              partName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              partDescription_ = s;
              break;
            }
            case 48: {

              inventoryCurrentCount_ = input.readInt32();
              break;
            }
            case 56: {

              inventoryDesiredCount_ = input.readInt32();
              break;
            }
            case 64: {

              discontinued_ = input.readBool();
              break;
            }
            case 72: {

              onOrder_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return carparts.proto.Schema.internal_static_carparts_proto_CarPart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return carparts.proto.Schema.internal_static_carparts_proto_CarPart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              carparts.proto.Schema.CarPart.class, carparts.proto.Schema.CarPart.Builder.class);
    }

    public static final int VENDORID_FIELD_NUMBER = 2;
    private int vendorId_;
    /**
     * <code>int32 vendorId = 2;</code>
     */
    public int getVendorId() {
      return vendorId_;
    }

    public static final int PARTID_FIELD_NUMBER = 3;
    private int partId_;
    /**
     * <code>int32 partId = 3;</code>
     */
    public int getPartId() {
      return partId_;
    }

    public static final int PARTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object partName_;
    /**
     * <code>string partName = 4;</code>
     */
    public java.lang.String getPartName() {
      java.lang.Object ref = partName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partName_ = s;
        return s;
      }
    }
    /**
     * <code>string partName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPartNameBytes() {
      java.lang.Object ref = partName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARTDESCRIPTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object partDescription_;
    /**
     * <code>string partDescription = 5;</code>
     */
    public java.lang.String getPartDescription() {
      java.lang.Object ref = partDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string partDescription = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPartDescriptionBytes() {
      java.lang.Object ref = partDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INVENTORYCURRENTCOUNT_FIELD_NUMBER = 6;
    private int inventoryCurrentCount_;
    /**
     * <code>int32 inventoryCurrentCount = 6;</code>
     */
    public int getInventoryCurrentCount() {
      return inventoryCurrentCount_;
    }

    public static final int INVENTORYDESIREDCOUNT_FIELD_NUMBER = 7;
    private int inventoryDesiredCount_;
    /**
     * <code>int32 inventoryDesiredCount = 7;</code>
     */
    public int getInventoryDesiredCount() {
      return inventoryDesiredCount_;
    }

    public static final int DISCONTINUED_FIELD_NUMBER = 8;
    private boolean discontinued_;
    /**
     * <code>bool discontinued = 8;</code>
     */
    public boolean getDiscontinued() {
      return discontinued_;
    }

    public static final int ONORDER_FIELD_NUMBER = 9;
    private boolean onOrder_;
    /**
     * <code>bool onOrder = 9;</code>
     */
    public boolean getOnOrder() {
      return onOrder_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vendorId_ != 0) {
        output.writeInt32(2, vendorId_);
      }
      if (partId_ != 0) {
        output.writeInt32(3, partId_);
      }
      if (!getPartNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, partName_);
      }
      if (!getPartDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, partDescription_);
      }
      if (inventoryCurrentCount_ != 0) {
        output.writeInt32(6, inventoryCurrentCount_);
      }
      if (inventoryDesiredCount_ != 0) {
        output.writeInt32(7, inventoryDesiredCount_);
      }
      if (discontinued_ != false) {
        output.writeBool(8, discontinued_);
      }
      if (onOrder_ != false) {
        output.writeBool(9, onOrder_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vendorId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, vendorId_);
      }
      if (partId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, partId_);
      }
      if (!getPartNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, partName_);
      }
      if (!getPartDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, partDescription_);
      }
      if (inventoryCurrentCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, inventoryCurrentCount_);
      }
      if (inventoryDesiredCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, inventoryDesiredCount_);
      }
      if (discontinued_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, discontinued_);
      }
      if (onOrder_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, onOrder_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof carparts.proto.Schema.CarPart)) {
        return super.equals(obj);
      }
      carparts.proto.Schema.CarPart other = (carparts.proto.Schema.CarPart) obj;

      boolean result = true;
      result = result && (getVendorId()
          == other.getVendorId());
      result = result && (getPartId()
          == other.getPartId());
      result = result && getPartName()
          .equals(other.getPartName());
      result = result && getPartDescription()
          .equals(other.getPartDescription());
      result = result && (getInventoryCurrentCount()
          == other.getInventoryCurrentCount());
      result = result && (getInventoryDesiredCount()
          == other.getInventoryDesiredCount());
      result = result && (getDiscontinued()
          == other.getDiscontinued());
      result = result && (getOnOrder()
          == other.getOnOrder());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VENDORID_FIELD_NUMBER;
      hash = (53 * hash) + getVendorId();
      hash = (37 * hash) + PARTID_FIELD_NUMBER;
      hash = (53 * hash) + getPartId();
      hash = (37 * hash) + PARTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPartName().hashCode();
      hash = (37 * hash) + PARTDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getPartDescription().hashCode();
      hash = (37 * hash) + INVENTORYCURRENTCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getInventoryCurrentCount();
      hash = (37 * hash) + INVENTORYDESIREDCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getInventoryDesiredCount();
      hash = (37 * hash) + DISCONTINUED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDiscontinued());
      hash = (37 * hash) + ONORDER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOnOrder());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static carparts.proto.Schema.CarPart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static carparts.proto.Schema.CarPart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static carparts.proto.Schema.CarPart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static carparts.proto.Schema.CarPart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static carparts.proto.Schema.CarPart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static carparts.proto.Schema.CarPart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static carparts.proto.Schema.CarPart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static carparts.proto.Schema.CarPart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static carparts.proto.Schema.CarPart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static carparts.proto.Schema.CarPart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static carparts.proto.Schema.CarPart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static carparts.proto.Schema.CarPart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(carparts.proto.Schema.CarPart prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code carparts.proto.CarPart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:carparts.proto.CarPart)
        carparts.proto.Schema.CarPartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return carparts.proto.Schema.internal_static_carparts_proto_CarPart_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return carparts.proto.Schema.internal_static_carparts_proto_CarPart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                carparts.proto.Schema.CarPart.class, carparts.proto.Schema.CarPart.Builder.class);
      }

      // Construct using carparts.proto.Schema.CarPart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vendorId_ = 0;

        partId_ = 0;

        partName_ = "";

        partDescription_ = "";

        inventoryCurrentCount_ = 0;

        inventoryDesiredCount_ = 0;

        discontinued_ = false;

        onOrder_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return carparts.proto.Schema.internal_static_carparts_proto_CarPart_descriptor;
      }

      @java.lang.Override
      public carparts.proto.Schema.CarPart getDefaultInstanceForType() {
        return carparts.proto.Schema.CarPart.getDefaultInstance();
      }

      @java.lang.Override
      public carparts.proto.Schema.CarPart build() {
        carparts.proto.Schema.CarPart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public carparts.proto.Schema.CarPart buildPartial() {
        carparts.proto.Schema.CarPart result = new carparts.proto.Schema.CarPart(this);
        result.vendorId_ = vendorId_;
        result.partId_ = partId_;
        result.partName_ = partName_;
        result.partDescription_ = partDescription_;
        result.inventoryCurrentCount_ = inventoryCurrentCount_;
        result.inventoryDesiredCount_ = inventoryDesiredCount_;
        result.discontinued_ = discontinued_;
        result.onOrder_ = onOrder_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof carparts.proto.Schema.CarPart) {
          return mergeFrom((carparts.proto.Schema.CarPart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(carparts.proto.Schema.CarPart other) {
        if (other == carparts.proto.Schema.CarPart.getDefaultInstance()) return this;
        if (other.getVendorId() != 0) {
          setVendorId(other.getVendorId());
        }
        if (other.getPartId() != 0) {
          setPartId(other.getPartId());
        }
        if (!other.getPartName().isEmpty()) {
          partName_ = other.partName_;
          onChanged();
        }
        if (!other.getPartDescription().isEmpty()) {
          partDescription_ = other.partDescription_;
          onChanged();
        }
        if (other.getInventoryCurrentCount() != 0) {
          setInventoryCurrentCount(other.getInventoryCurrentCount());
        }
        if (other.getInventoryDesiredCount() != 0) {
          setInventoryDesiredCount(other.getInventoryDesiredCount());
        }
        if (other.getDiscontinued() != false) {
          setDiscontinued(other.getDiscontinued());
        }
        if (other.getOnOrder() != false) {
          setOnOrder(other.getOnOrder());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        carparts.proto.Schema.CarPart parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (carparts.proto.Schema.CarPart) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int vendorId_ ;
      /**
       * <code>int32 vendorId = 2;</code>
       */
      public int getVendorId() {
        return vendorId_;
      }
      /**
       * <code>int32 vendorId = 2;</code>
       */
      public Builder setVendorId(int value) {
        
        vendorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 vendorId = 2;</code>
       */
      public Builder clearVendorId() {
        
        vendorId_ = 0;
        onChanged();
        return this;
      }

      private int partId_ ;
      /**
       * <code>int32 partId = 3;</code>
       */
      public int getPartId() {
        return partId_;
      }
      /**
       * <code>int32 partId = 3;</code>
       */
      public Builder setPartId(int value) {
        
        partId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 partId = 3;</code>
       */
      public Builder clearPartId() {
        
        partId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object partName_ = "";
      /**
       * <code>string partName = 4;</code>
       */
      public java.lang.String getPartName() {
        java.lang.Object ref = partName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          partName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string partName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPartNameBytes() {
        java.lang.Object ref = partName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string partName = 4;</code>
       */
      public Builder setPartName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string partName = 4;</code>
       */
      public Builder clearPartName() {
        
        partName_ = getDefaultInstance().getPartName();
        onChanged();
        return this;
      }
      /**
       * <code>string partName = 4;</code>
       */
      public Builder setPartNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        partName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object partDescription_ = "";
      /**
       * <code>string partDescription = 5;</code>
       */
      public java.lang.String getPartDescription() {
        java.lang.Object ref = partDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          partDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string partDescription = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPartDescriptionBytes() {
        java.lang.Object ref = partDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string partDescription = 5;</code>
       */
      public Builder setPartDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string partDescription = 5;</code>
       */
      public Builder clearPartDescription() {
        
        partDescription_ = getDefaultInstance().getPartDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string partDescription = 5;</code>
       */
      public Builder setPartDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        partDescription_ = value;
        onChanged();
        return this;
      }

      private int inventoryCurrentCount_ ;
      /**
       * <code>int32 inventoryCurrentCount = 6;</code>
       */
      public int getInventoryCurrentCount() {
        return inventoryCurrentCount_;
      }
      /**
       * <code>int32 inventoryCurrentCount = 6;</code>
       */
      public Builder setInventoryCurrentCount(int value) {
        
        inventoryCurrentCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 inventoryCurrentCount = 6;</code>
       */
      public Builder clearInventoryCurrentCount() {
        
        inventoryCurrentCount_ = 0;
        onChanged();
        return this;
      }

      private int inventoryDesiredCount_ ;
      /**
       * <code>int32 inventoryDesiredCount = 7;</code>
       */
      public int getInventoryDesiredCount() {
        return inventoryDesiredCount_;
      }
      /**
       * <code>int32 inventoryDesiredCount = 7;</code>
       */
      public Builder setInventoryDesiredCount(int value) {
        
        inventoryDesiredCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 inventoryDesiredCount = 7;</code>
       */
      public Builder clearInventoryDesiredCount() {
        
        inventoryDesiredCount_ = 0;
        onChanged();
        return this;
      }

      private boolean discontinued_ ;
      /**
       * <code>bool discontinued = 8;</code>
       */
      public boolean getDiscontinued() {
        return discontinued_;
      }
      /**
       * <code>bool discontinued = 8;</code>
       */
      public Builder setDiscontinued(boolean value) {
        
        discontinued_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool discontinued = 8;</code>
       */
      public Builder clearDiscontinued() {
        
        discontinued_ = false;
        onChanged();
        return this;
      }

      private boolean onOrder_ ;
      /**
       * <code>bool onOrder = 9;</code>
       */
      public boolean getOnOrder() {
        return onOrder_;
      }
      /**
       * <code>bool onOrder = 9;</code>
       */
      public Builder setOnOrder(boolean value) {
        
        onOrder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool onOrder = 9;</code>
       */
      public Builder clearOnOrder() {
        
        onOrder_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:carparts.proto.CarPart)
    }

    // @@protoc_insertion_point(class_scope:carparts.proto.CarPart)
    private static final carparts.proto.Schema.CarPart DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new carparts.proto.Schema.CarPart();
    }

    public static carparts.proto.Schema.CarPart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarPart>
        PARSER = new com.google.protobuf.AbstractParser<CarPart>() {
      @java.lang.Override
      public CarPart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarPart(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarPart> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarPart> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public carparts.proto.Schema.CarPart getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carparts_proto_CarParts_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carparts_proto_CarParts_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carparts_proto_CarPart_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carparts_proto_CarPart_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\016carparts.proto\"4\n\010CarPar" +
      "ts\022(\n\007carPart\030\001 \003(\0132\027.carparts.proto.Car" +
      "Part\"\273\001\n\007CarPart\022\020\n\010vendorId\030\002 \001(\005\022\016\n\006pa" +
      "rtId\030\003 \001(\005\022\020\n\010partName\030\004 \001(\t\022\027\n\017partDesc" +
      "ription\030\005 \001(\t\022\035\n\025inventoryCurrentCount\030\006" +
      " \001(\005\022\035\n\025inventoryDesiredCount\030\007 \001(\005\022\024\n\014d" +
      "iscontinued\030\010 \001(\010\022\017\n\007onOrder\030\t \001(\010b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_carparts_proto_CarParts_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_carparts_proto_CarParts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carparts_proto_CarParts_descriptor,
        new java.lang.String[] { "CarPart", });
    internal_static_carparts_proto_CarPart_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_carparts_proto_CarPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carparts_proto_CarPart_descriptor,
        new java.lang.String[] { "VendorId", "PartId", "PartName", "PartDescription", "InventoryCurrentCount", "InventoryDesiredCount", "Discontinued", "OnOrder", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
